AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Parent Stack of the ECS Cluster example

Parameters:
  BucketName:
    Description: Name of the CloudFormation Template Bucket generated in bootstrap stack
    Type: String

Conditions:
  EnableALB: !Equals ["", "1"]

Resources:
  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${BucketName}.s3.${AWS::Region}.amazonaws.com/02-ecs-ec2-cluster.yml"

  ALBStack:
    Condition: EnableALB
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${BucketName}.s3.${AWS::Region}.amazonaws.com/03-nginx-alb.yml"

  EFSStack:
    #
    # CloudFormation Reference: AWS::CloudFormation::Stack
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stack.html
    #
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${BucketName}.s3.${AWS::Region}.amazonaws.com/04-efs-nginx-shared.yml"
      #Parameters:
      #Tags:
      #TimeoutInMinutes:
      #NotificationARNs:

  NginxECSSvcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${BucketName}.s3.${AWS::Region}.amazonaws.com/05-nginx-ecs-svc.yml"
      Parameters:
        EFSSharedFileSystemId: !GetAtt EFSStack.Outputs.FileSystemId
        SiteContentAccessPointId: !GetAtt EFSStack.Outputs.SiteContentAPId
        ECSClusterArn: !GetAtt ECSClusterStack.Outputs.ClusterArn
        EFSClientSecurityGroupId: !GetAtt EFSStack.Outputs.EFSClientSGId
        ALBForwardSecurityGroupId: !If [EnableALB, !GetAtt ALBStack.Outputs.ALBForwardSecurityGroupId, !Ref "AWS::NoValue"]
        TargetGroupArn: !If [EnableALB, !GetAtt ALBStack.Outputs.TargetGroupArn, !Ref "AWS::NoValue"]

Outputs:
  SshKeyPairId:
    Value: !GetAtt ECSClusterStack.Outputs.SshKeyPairId

  ALBPublicDomainName:
    Condition: EnableALB
    Value: !GetAtt ALBStack.Outputs.ALBDNSName

  ECSClusterStackArn:
    Value: !Ref ECSClusterStack

  ALBStackArn:
    Condition: EnableALB
    Value: !Ref ALBStack

  EFSStackArn:
    Value: !Ref EFSStack

  NginxServiceStackArn:
    Value: !Ref NginxECSSvcStack

  # EFSStackOutputs: 
  #   Value: !GetAtt EFSStack.Outputs

  # ASGStackId:
  #   Value: !GetAtt ASGEC2NodeStack.StackId

  # ASGStackOutputs: 
  #   Value: !GetAtt ASGEC2NodeStack.Outputs