AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Parent Stack of the ECS Cluster example

Parameters:
  TemplateBucketBaseUrl:
    Type: String
    Default: https://esc-ec2-cluster-cfn-templates.s3.eu-north-1.amazonaws.com

Resources:
  EFSStack:
    #
    # CloudFormation Reference: AWS::CloudFormation::Stack
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stack.html
    #
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/efs-nginx-shared.yml"
      #Parameters:
      #Tags:
      #TimeoutInMinutes:
      #NotificationARNs:

  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/ecs-ec2-cluster.yml"

  NginxECSSvcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/nginx-ecs-svc.yml"
      Parameters:
        EFSSharedFileSystemId: !GetAtt EFSStack.Outputs.FileSystemId
        SiteContentAccessPointId: !GetAtt EFSStack.Outputs.SiteContentAPId
        ECSClusterArn: !GetAtt ECSClusterStack.Outputs.ClusterArn
        EFSClientSecurityGroupId: !GetAtt EFSStack.Outputs.EFSClientSGId

Outputs:
  EFSStackArn:
     Value: !Ref EFSStack

  ECSClusterStack:
     Value: !Ref ECSClusterStack

  # EFSStackOutputs: 
  #   Value: !GetAtt EFSStack.Outputs

  # ASGStackId:
  #   Value: !GetAtt ASGEC2NodeStack.StackId

  # ASGStackOutputs: 
  #   Value: !GetAtt ASGEC2NodeStack.Outputs